export enum EventNames {
  SNAPSHOT = 'snapshot',
  DELTA = 'delta',
  INPUT = 'input',
  JOIN_REQUEST = 'join_request',
  JOIN_RESPONSE = 'join_response',
  HOST_START = 'host:start',
  CLASS_SELECT = 'class:select',
  COOLDOWN_UPDATE = 'cooldown:update',
  SPIRIT_FORM = 'spirit:form',
  RUN_PROPOSE          = 'run:propose',
  VOTE                 = 'run:vote',
  RUN_ABANDON_PROPOSE  = 'run:abandon-propose',
  RUN_ABANDON_VOTE     = 'run:abandon-vote',
  RUN_STARTING         = 'run:starting',
  RETURN_TO_CAMP = 'return:to-camp',
  CONTINUE = 'bond:continue',
  BOND_NOTIFICATION = 'bond:notification',
  RUN_VICTORY = 'run:victory',
}
